
### mrkmat/dotfiles

set -x NODE_ENV development

alias gs='git status'
alias gp='git pull'
alias ga='git add .'
alias gap='git add -p'
alias gm='git merge --no-ff'
alias gc='git changelog'
alias gg='git graph'
alias gcm='git checkout master'
alias gsm='git submodule update --init --recursive'
alias gup='git pull --rebase --prune ; and gsm'
alias hash='git rev-parse --short HEAD | pbcopy'
alias eh='sudo vim /etc/hosts'
alias c='code .'
alias r='rider .'
alias ..='cd ..'
alias v='vtex'
alias vl='vtex link --verbose'
alias vu='vtex unlink -a'
alias toolbelt='cd ~/vtex/toolbelt'
alias billing='cd ~/vtex/billing-app'
alias builder='cd ~/vtex/builder-hub'
alias admin='cd ~/vtex/admin'
alias vwls='vtex workspace ls'
alias vls='vtex ls --verbose'
alias prod='vtex production'
alias prom='vtex promote'
alias vwrs='vtex workspace reset'
alias prodprom='prod; echo y | prom'
alias vum='echo y | vtex use mark'
alias vum1='echo y | vtex use mark1'
alias vum2='echo y | vtex use mark2'
alias vumaster='echo y | vtex use master'
alias vd='vtex workspace use master; echo y | vtex workspace delete'
alias vdm='vtex workspace use master; echo y | vtex workspace delete mark'
alias vdm1='vtex workspace use master; echo y | vtex workspace delete mark1'
alias vdm2='vtex workspace use master; echo y | vtex workspace delete mark2'
alias myalias='c ~/.config/fish/config.fish'
alias ec='echo | get_vtex_workspace'
alias hb='hub browse'
alias checkdep='vtex deps ls | grep -A 5'
alias token='vtex local token'
alias configprod='vtex config set env prod'
alias configstaging='vtex config set env staging'
alias linkvtex='toolbelt; yarn unlink --silent; cd -; cd /usr/local/lib/node_modules/vtex/; yarn link --silent; cd -'
test -e {$HOME}/.iterm2_shell_integration.fish ; and source {$HOME}/.iterm2_shell_integration.fish
export GITHUB_API_TOKEN=00d961a0f66528d32714ab6c626aa7a21a18e77f